name: CI Test for Calculator  

on:  
  push:  
    branches:  
      - main  
  pull_request:  
    branches:  
      - main  

jobs:  
  test:  
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment  

    steps:  
      # Step 1: Checkout the repository  
      - name: Checkout repository  
        uses: actions/checkout@v3  

      # Step 2: Setup Python environment  
      - name: Setup Python  
        uses: actions/setup-python@v4  
        with:  
          python-version: '3.9'  # Specify the Python version  

      # Step 3: Install dependencies  
      - name: Install dependencies  
        run: |  
          python -m pip install --upgrade pip  
          pip install behave  # Install Behave  

      # Step 4: Run Behave tests  
      - name: Run Tests  
        run: |  
          mkdir -p test-results  # Ensure the directory exists
